### ISSUE TITLE
Problems connecting with SSL

### ISSUE THREAD

**Issue by carloabelli** [psychs/limechat#235]
I am trying to connect to [freenode](http://freenode.net/irc_servers.shtml) using SSL, but I am getting errors doing so. I have succeeded in connecting once over SSL (after a couple of the errors below), but I have been unable to reproduce a successful connection since.

A normal connect using the following options works perfectly fine.
Server Properties:
![screen shot 2014-07-08 at 7 07 36 pm](https://cloud.githubusercontent.com/assets/3083317/3517817/8d6bf156-06f5-11e4-8292-b31765f54436.png)
Output:

```
*** Looking up your hostname...
*** Checking Ident
*** Found your hostname
*** No Ident response
You are now logged in as cabellicar123.
SASL authentication successful
Logged in
Welcome to the freenode Internet Relay Chat Network cabellicar123
```

However if I switch to SSL I get an error.
Server Properties:
![screen shot 2014-07-08 at 7 10 45 pm](https://cloud.githubusercontent.com/assets/3083317/3517826/a722cdea-06f5-11e4-8f22-0cebad7e5949.png)
Output:

```
Connecting…
Connected
The operation couldn’t be completed. (OSStatus error -9847.)
Disconnected
```

And if I switch to a SSL only port for freenode (ex. `7070`) I get a different error.
Server Properties:
![screen shot 2014-07-08 at 7 18 26 pm](https://cloud.githubusercontent.com/assets/3083317/3517863/3cf28ffe-06f6-11e4-9ae5-c8d5b6d00e54.png)
Output:

```
Connected
The operation couldn’t be completed. (OSStatus error -9806.)
Disconnected
```

**Comment by stantonk** [comment]
+1 had same issue on OS X El Capitan 10.11.6 when trying port 6667. Port 7000 works.

**Comment by emanaku** [comment]
Try 6697 ;-)

**Comment by Bischoff** [comment]
Same here, Mac OS X High Sierra 10.13.6. I know for sure the SSL port number that I am trying to connect to (it works on another OS).
```
11:32 <irc.****.****> The operation couldn’t be completed. (OSStatus error -9824.)
```
I am convinced the new Mac OS uses a different TLS version which is not supported by some servers. Could there be a way to force LimeChat to an older version?

**Comment by FrancoisRab** [comment]
Hello, on MacOS Mojave 10.14.1 port 7070 works with SSL Connection.

**Comment by Bischoff** [comment]
@FrancoisRab I suppose it depends on the IRC server you're trying to connect to. If that server supports a recent TLS, it can work with Mac OS X. If it uses an old SSL, the connection will fail.

The port number (7070 or whatever) is irrelevant.

**Comment by BigslimVdub** [comment]
6697 works on high sierra for freenode.net

**Comment by Bischoff** [comment]
Again, this depends on the server you are using.

**Comment by borayds** [comment]
> 6697 works on high sierra for freenode.net

I confirm that SSL works with Limechat port 6697 on freenode server using Mojave.

**Comment by FelipeMiranda** [comment]
> > 6697 works on high sierra for freenode.net
> 
> I confirm that SSL works with Limechat port 6697 on freenode server using Mojave.

It does not work for me!

LimeChat 2.43
Mojave 10.14.4
Server: chat.freenode.net
Port: 6697 SSL Enabled
Use SASL Enabled

**Comment by BigslimVdub** [comment]
LimeChat IoS Freenode and port 6697 ssl does not work
