### ISSUE TITLE
use of undeclared identifier '_hidden'

### ISSUE THREAD

**Issue by bsdshell** [psychs/limechat#270]
I try to build the App and get following error:
use of undeclared identifier '_hidden'

Xcode 6.1.1

**Comment by bsdshell** [comment]
it needs this line in ThinSplitView.m to compile  (Xcode 6.1.1)
@synthesize hidden = _hidden;

**Comment by dburkart** [comment]
I opened a pull request that resolves this:

https://github.com/psychs/limechat/pull/271

**Comment by bsdshell** [comment]
Thanks:)
