### ISSUE TITLE
Growl Not Working

### ISSUE THREAD

**Issue by dr4g0nnn** [psychs/limechat#61]
It seems that the Growl notifications aren't working (or at least, no properly) in the latest version, both on Highlights and New Talk.

Growl is working properly for other applications, it's just Limechat that's not doing it.

**Comment by joech4n** [comment]
This seems to be broken for me now in OSX 10.9.5 and Limechat 2.42 and Growl 2.1.3.

Limechat doesn't appear to be registered in Growl, any ideas what may be wrong here?
